# Generated by Django 4.2.30 on 2026-06-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('secondname', models.CharField()),
                ('firstname', models.CharField()),
                ('phone', models.IntegerField()),
                ('bday', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField()),
                ('pass_field', models.CharField(db_column='pass')),
                ('isadmin', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
